project:
  type: website
  output-dir: docs

website:
  title: "BCB504Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bcmommy42
      
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

